// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6i-OmL-1uRxJOVmq32V2RmeUX7aLdRrE',
    appId: '1:127973270666:ios:3bbf0941ed0a66a9343973',
    messagingSenderId: '127973270666',
    projectId: 'learnloop-9b70a',
    storageBucket: 'learnloop-9b70a.firebasestorage.app',
    iosBundleId: 'com.ahmad.learnLoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuK5fd2z9rpzLJQ-wv7Xr7VfV0PS_dm-k',
    appId: '1:127973270666:web:c5826ee8387331f1343973',
    messagingSenderId: '127973270666',
    projectId: 'learnloop-9b70a',
    authDomain: 'learnloop-9b70a.firebaseapp.com',
    storageBucket: 'learnloop-9b70a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuK5fd2z9rpzLJQ-wv7Xr7VfV0PS_dm-k',
    appId: '1:127973270666:web:c5826ee8387331f1343973',
    messagingSenderId: '127973270666',
    projectId: 'learnloop-9b70a',
    authDomain: 'learnloop-9b70a.firebaseapp.com',
    storageBucket: 'learnloop-9b70a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6i-OmL-1uRxJOVmq32V2RmeUX7aLdRrE',
    appId: '1:127973270666:ios:3bbf0941ed0a66a9343973',
    messagingSenderId: '127973270666',
    projectId: 'learnloop-9b70a',
    storageBucket: 'learnloop-9b70a.firebasestorage.app',
    iosBundleId: 'com.ahmad.learnLoop',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGubKXU2CRunqy88OuRd35VPVZIqtRBuE',
    appId: '1:127973270666:android:8737cc646f2848f6343973',
    messagingSenderId: '127973270666',
    projectId: 'learnloop-9b70a',
    storageBucket: 'learnloop-9b70a.firebasestorage.app',
  );

}